# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashcan',
            name='name',
            field=models.CharField(default='joe', max_length=30),
            preserve_default=False,
        ),
    ]
