# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_trashcan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashcan',
            name='location',
            field=models.CharField(default='China', max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trashcan',
            name='installDate',
            field=models.DateTimeField(verbose_name='installed'),
        ),
    ]
