# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20170710_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trashcan',
            name='trashID',
            field=models.IntegerField(default='1'),
        ),
    ]
