# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-17 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields
import processing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrashCan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', jsonfield.fields.JSONField(blank=True, default=processing.models.json_default, null=True)),
                ('payload', jsonfield.fields.JSONField(blank=True, default=processing.models.json_default, null=True)),
            ],
        ),
    ]
