# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-18 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import processing.models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0002_trashcan_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashcan',
            name='fillLevel',
            field=models.DecimalField(decimal_places=3, default=processing.models.dec_default, max_digits=6),
        ),
        migrations.AddField(
            model_name='trashcan',
            name='fillStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trashcan',
            name='installDate',
            field=models.DateTimeField(default=processing.models.date_default, verbose_name='installed'),
        ),
        migrations.AddField(
            model_name='trashcan',
            name='lastEmptied',
            field=models.DateTimeField(default=processing.models.date_default, verbose_name='last emptied'),
        ),
        migrations.AddField(
            model_name='trashcan',
            name='lastUpdated',
            field=models.DateTimeField(default=processing.models.date_default, verbose_name='last updated'),
        ),
        migrations.AddField(
            model_name='trashcan',
            name='latitude',
            field=models.DecimalField(decimal_places=7, default=processing.models.dec_default, max_digits=11),
        ),
        migrations.AddField(
            model_name='trashcan',
            name='location',
            field=models.CharField(default='101 Estudillo Avenue', max_length=400),
        ),
        migrations.AddField(
            model_name='trashcan',
            name='longitude',
            field=models.DecimalField(decimal_places=7, default=processing.models.dec_default, max_digits=11),
        ),
        migrations.AddField(
            model_name='trashcan',
            name='maxFill',
            field=models.DecimalField(decimal_places=3, default=processing.models.dec_default, max_digits=6),
        ),
        migrations.AddField(
            model_name='trashcan',
            name='name',
            field=models.CharField(default='MiDro', max_length=100),
        ),
        migrations.AddField(
            model_name='trashcan',
            name='percent',
            field=models.DecimalField(decimal_places=3, default=processing.models.dec_default, max_digits=6),
        ),
        migrations.AddField(
            model_name='trashcan',
            name='sensor1',
            field=models.DecimalField(decimal_places=5, default=processing.models.dec_default, max_digits=10),
        ),
        migrations.AddField(
            model_name='trashcan',
            name='sensor2',
            field=models.DecimalField(decimal_places=5, default=processing.models.dec_default, max_digits=10),
        ),
        migrations.AddField(
            model_name='trashcan',
            name='sensor3',
            field=models.DecimalField(decimal_places=5, default=processing.models.dec_default, max_digits=10),
        ),
        migrations.AddField(
            model_name='trashcan',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trashcan',
            name='trashID',
            field=models.IntegerField(default=-1),
        ),
    ]
