# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 00:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processing', '0002_auto_20170710_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashcan',
            name='owners',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='trashcans', to=settings.AUTH_USER_MODEL),
        ),
    ]
