# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-18 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0003_auto_20170718_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashcan',
            name='macAddress',
            field=models.CharField(default='MiDro', max_length=50),
        ),
        migrations.AddField(
            model_name='trashcan',
            name='messageID',
            field=models.CharField(default='MiDro', max_length=200),
        ),
        migrations.AddField(
            model_name='trashcan',
            name='sensorID',
            field=models.CharField(default='MiDro', max_length=50),
        ),
    ]
