# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 00:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0003_trashcan_owners'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trashcan',
            old_name='owners',
            new_name='owner',
        ),
    ]
