# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 21:50
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields
import processing.models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0004_auto_20170711_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashcan',
            name='json',
            field=jsonfield.fields.JSONField(default=processing.models.my_default),
        ),
    ]
