# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-18 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0005_auto_20170718_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashcan',
            name='bn',
            field=models.CharField(default='101 Estudillo Avenue', max_length=100),
        ),
    ]
