# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 22:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0006_trashcan_paylod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trashcan',
            old_name='paylod',
            new_name='payload',
        ),
    ]
