# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-21 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0006_trashcan_bn'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashcan',
            name='info',
            field=models.CharField(default='101 Estudillo Avenue', max_length=1000),
        ),
        migrations.AddField(
            model_name='trashcan',
            name='webID',
            field=models.CharField(default='101 Estudillo Avenue', max_length=400),
        ),
    ]
