# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import processing.models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0007_auto_20170721_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trashcan',
            name='fillLevel',
            field=models.DecimalField(decimal_places=3, default=processing.models.dec_default, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trashcan',
            name='maxFill',
            field=models.DecimalField(decimal_places=3, default=processing.models.dec_default, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trashcan',
            name='percent',
            field=models.DecimalField(decimal_places=3, default=processing.models.dec_default, max_digits=10),
        ),
    ]
