# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-08 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0007_auto_20171204_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=70)),
                ('role', models.IntegerField()),
            ],
        ),
    ]
